include:
  - project: shared/ci
    ref: release/1.0
    file:
      - image/kaniko.yaml

stages:
  - image
  - verify
  - test
  - analyze

variables:
  TEST_NOTES:
    description: "Доп. информация о тесте (JIRA ID, описание)"
    value: ""    
  SERVICE_TO_TEST:
    description: "Сервис для тестирования"
    options:
      - "dummy"
      - "service_a"
      - "service_b"
      
    value: "dummy"
  TEST_TYPE:
    description: "Тип теста: stability | load | max | JIRA-ID"
    value: "dummy"

  IMAGE_TAG: "${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_REF_NAME}"
  JMETER_HEAP: "-Xms6g -Xmx10g"
  JVM_ARGS: "-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:G1ReservePercent=20 -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.trustStore=/jmeter/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit"

# Проверка образа
verify_image:
  stage: verify
  image: "${IMAGE_TAG}"
  script:
    - echo "🔍 Проверка JMeter образа..."
    - jmeter -v
    - echo "📂 Проверка структуры директорий..."
    - ls -la /jmeter/tests/
    - ls -la /jmeter/conf/
    - ls -la /jmeter/utils/
    - echo "✅ Образ проверен и готов к использованию"
  allow_failure: false

# Запуск теста
test:
  stage: test
  tags:
    - loadtest
  image: "${IMAGE_TAG}"
  needs: ["verify_image"]
  variables:
    RESULTS_DIR: "results/${SERVICE_TO_TEST}/${TEST_TYPE}"
    JTL_FILE: "${RESULTS_DIR}/results.jtl"
    LOG_FILE: "${RESULTS_DIR}/jmeter.log"
    HTML_DIR: "${RESULTS_DIR}/html"
    NOTES: "${RESULTS_DIR}/notes.md"
    TEST_START_TIME: ${CI_JOB_STARTED_AT}
  before_script:
    - export RUNNER_NAME=$(hostname)
    - echo "=== Метрики запущенных тестов доступны по адресу ==="
    - echo "📊 👁️ https://grafana.test.com/d/6581e46eb23/kubernetes-compute-resources-pod?orgId=1&from=now-1h&to=now&timezone=UTC&var-datasource=F997E84B62F&var-cluster=com-test-c1-es-02&var-namespace=gitlab-runners&var-pod=${RUNNER_NAME}"
  script:
    - echo "=== Запуск JMeter ==="
    - echo "📌 Тестирование сервиса ${SERVICE_TO_TEST}"
    - echo "📌 Тестовый скрипт ${TEST_TYPE}"
    - echo "📌 Дополнительная информация ${TEST_NOTES}"
    - echo "📌 Время начала ${TEST_START_TIME}"

    - |
      TEST_PLAN="tests/${SERVICE_TO_TEST}/${TEST_TYPE}.jmx"
      if [ ! -f "$TEST_PLAN" ]; then
        echo "❌ Ошибка: не найден тест-план $TEST_PLAN"
        echo "📁 Доступные тест-планы:"
        find tests -name "*.jmx" -type f 2>/dev/null || echo "Нет .jmx файлов"
        exit 1
      fi
      echo "✅ Тест-план: $TEST_PLAN найден"
    
    - mkdir -p "${RESULTS_DIR}"
    
    - |
      # Подключаем файлы свойств
      if [ -f "conf/global.properties" ]; then
        PROPS="-q conf/global.properties"
        echo "✅ Найден файл глобальных свойств"
      else
        PROPS=""
        echo "⚠️ Файл глобальных свойств не найден"
      fi
      
      # Пути к файлам данных
      if [ -f "conf/files.properties" ]; then
        PROPS="${PROPS} -q conf/files.properties"
        echo "✅ Подключен файл путей к данным"
      else
        echo "⚠️ Файл путей к данным не найден"
      fi

      echo "🔧 Итоговые параметры properties: ${PROPS}"

    - |
      # JMeter properties
      JPROPS="-Jproject.name=${SERVICE_TO_TEST}"
      JPROPS="$JPROPS -Jtest.name=${TEST_TYPE}"
      JPROPS="$JPROPS -Jtest.ci_pipeline_id=${CI_PIPELINE_ID}"
      JPROPS="$JPROPS -Jtest.ci_job_id=${CI_JOB_ID}"
      JPROPS="$JPROPS -Jtest.start_time=${TEST_START_TIME}"
    
    - |
      # Экспорт JVM настроек
      export HEAP="${JMETER_HEAP}"
      export JVM_ARGS="${JVM_ARGS}"
      
      echo "🚀 Запуск JMeter..."
      echo "Используемая команда: jmeter -n -t $TEST_PLAN $PROPS $JPROPS -l ${JTL_FILE} -j ${LOG_FILE} -e -o ${HTML_DIR}"
      
      # Запуск JMeter в foreground
      set -o pipefail
      jmeter -n -t "$TEST_PLAN" $PROPS $JPROPS \
        -l "${JTL_FILE}" \
        -j "${LOG_FILE}" \
        -e -o "${HTML_DIR}" | tee "${RESULTS_DIR}/console.log"
      
      TEST_EXIT_CODE=$?
      if [ $TEST_EXIT_CODE -eq 0 ]; then
        echo "✅ Тест завершён успешно"
      else
        echo "❌ Тест завершился с ошибкой (код $TEST_EXIT_CODE)"
        exit $TEST_EXIT_CODE
      fi
    
    - |
      # Проверяем результаты
      if [ -f "${JTL_FILE}" ]; then
        RECORDS=$(wc -l < ${JTL_FILE})
        echo "📊 Сгенерирован JTL: ${JTL_FILE} ($RECORDS строк)"
        
        # Проверка на минимальное количество записей
        if [ $RECORDS -lt 10 ]; then
          echo "⚠️ Внимание: файл результатов содержит менее 10 записей!"
        fi
      else
        echo "❌ JTL файл не создан!"
        exit 1
      fi
      
      if [ -d "${HTML_DIR}" ]; then
        echo "📈 Сгенерирован HTML отчёт: ${HTML_DIR}/"
      else
        echo "⚠️  HTML отчёт не создан"
      fi
      
      echo $TEST_NOTES > ${NOTES}
  
  artifacts:
    when: always
    expire_in: 14 days
    paths:
      - ${RESULTS_DIR}/

# Анализ результатов
analyze:
  stage: analyze
  image: company.test.com/docker/python:3.12-slim
  needs: ["test"]
  variables:
    RESULTS_DIR: "results/${SERVICE_TO_TEST}/${TEST_TYPE}"
    JTL_FILE: "${RESULTS_DIR}/results.jtl"
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install pandas
  script:
    - echo "🔍 Анализ результатов теста..."
    - |
      if [ ! -f "${JTL_FILE}" ]; then
        echo "❌ Файл результатов не найден: ${JTL_FILE}"
        exit 1
      fi
      
      echo "📊 Найден JTL файл: ${JTL_FILE}"
      echo "📝 Размер файла: $(du -h ${JTL_FILE})"
      
      RECORDS=$(wc -l < ${JTL_FILE})
      echo "📄 Количество записей: $RECORDS"
    - |
      # Проверяем наличие анализатора
      if [ ! -f "utils/jmeter_log_parser.py" ]; then
        echo "❌ Анализатор не найден: utils/jmeter_log_parser.py"
        echo "📁 Доступные файлы в utils/:"
        ls -la utils/ 2>/dev/null || echo "Папка utils не найдена"
        echo "⚠️ Анализ результатов невозможен без анализатора"
      else
        echo "✅ Найден анализатор: utils/jmeter_log_parser.py"
        python utils/jmeter_log_parser.py "${JTL_FILE}" --output-dir "${RESULTS_DIR}"
      fi
    
    - echo "✅ Анализ завершён"
    - echo "📊 Результаты анализа доступны в ${RESULTS_DIR}/"
  
  artifacts:
    when: on_success
    expire_in: 14 days
    paths:
      - ${RESULTS_DIR}/
